// Code generated by "enumer -type=PaymentStatus -json"; DO NOT EDIT.

package barion

import (
	"encoding/json"
	"fmt"
)

func (i PaymentStatus) String() string {
	switch i {
	case Prepared:
		return "Prepared"
	case Started:
		return "Started"
	case InProgress:
		return "InProgress"
	case Waiting:
		return "Waiting"
	case Reserved:
		return "Reserved"
	case Authorized:
		return "Authorized"
	case Canceled:
		return "Canceled"
	case Succeeded:
		return "Succeeded"
	case Failed:
		return "Failed"
	case PartiallySucceeded:
		return "PartiallySucceeded"
	case Expired:
		return "Expired"
	default:
		return fmt.Sprintf("PaymentStatus(%d)", i)
	}
}

var _PaymentStatusValues = []PaymentStatus{
	Prepared,
	Started,
	InProgress,
	Waiting,
	Reserved,
	Authorized,
	Canceled,
	Succeeded,
	Failed,
	PartiallySucceeded,
	Expired,
}

var _PaymentStatusNameToValueMap = map[string]PaymentStatus{
	"Prepared":           Prepared,
	"Started":            Started,
	"InProgress":         InProgress,
	"Waiting":            Waiting,
	"Reserved":           Reserved,
	"Authorized":         Authorized,
	"Canceled":           Canceled,
	"Succeeded":          Succeeded,
	"Failed":             Failed,
	"PartiallySucceeded": PartiallySucceeded,
	"Expired":            Expired,
}

// PaymentStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PaymentStatusString(s string) (PaymentStatus, error) {
	if val, ok := _PaymentStatusNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PaymentStatus values", s)
}

// PaymentStatusValues returns all values of the enum
func PaymentStatusValues() []PaymentStatus {
	return _PaymentStatusValues
}

// IsAPaymentStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PaymentStatus) IsAPaymentStatus() bool {
	for _, v := range _PaymentStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PaymentStatus
func (i PaymentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PaymentStatus
func (i *PaymentStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PaymentStatus should be a string, got %s", data)
	}

	var err error
	*i, err = PaymentStatusString(s)
	return err
}
