package barion

// TransactionType enumerates transaction type identifiers used by the Barion API.
type TransactionType string

const (
	TransactionTypeCommission                            TransactionType = "Commission"
	TransactionTypeShop                                  TransactionType = "Shop"
	TransactionTypeTransferToExistingUser                TransactionType = "TransferToExistingUser"
	TransactionTypeTransferToTechnicalAccount            TransactionType = "TransferToTechnicalAccount"
	TransactionTypeTransferFromTechnicalAccount          TransactionType = "TransferFromTechnicalAccount"
	TransactionTypeStorno                                TransactionType = "Storno"
	TransactionTypeWithdrawFee                           TransactionType = "WithdrawFee"
	TransactionTypeClosureFee                            TransactionType = "ClosureFee"
	TransactionTypeStornoBankTransferFee                 TransactionType = "StornoBankTransferFee"
	TransactionTypeCashDepositFee                        TransactionType = "CashDepositFee"
	TransactionTypeForeignDepositFee                     TransactionType = "ForeignDepositFee"
	TransactionTypeForeignWithdrawFee                    TransactionType = "ForeignWithdrawFee"
	TransactionTypeForeignClosureFee                     TransactionType = "ForeignClosureFee"
	TransactionTypeReserve                               TransactionType = "Reserve"
	TransactionTypeStornoReserve                         TransactionType = "StornoReserve"
	TransactionTypeCardTopUpFee                          TransactionType = "CardTopUpFee"
	TransactionTypeCardProcessingFee                     TransactionType = "CardProcessingFee"
	TransactionTypeGatewayFee                            TransactionType = "GatewayFee"
	TransactionTypeCardProcessingFeeStorno               TransactionType = "CardProcessingFeeStorno"
	TransactionTypeUnspecified                           TransactionType = "Unspecified"
	TransactionTypeIn                                    TransactionType = "In"
	TransactionTypeWithdraw                              TransactionType = "Withdraw"
	TransactionTypeCashDeposit                           TransactionType = "CashDeposit"
	TransactionTypeForeignDeposit                        TransactionType = "ForeignDeposit"
	TransactionTypeForeignBankTransferFee                TransactionType = "ForeignBankTransferFee"
	TransactionTypeCashBankTransferFee                   TransactionType = "CashBankTransferFee"
	TransactionTypeCustodyFee                            TransactionType = "CustodyFee"
	TransactionTypeForeignWithdraw                       TransactionType = "ForeignWithdraw"
	TransactionTypeTransferBack                          TransactionType = "TransferBack"
	TransactionTypeCardTopUp                             TransactionType = "CardTopUp"
	TransactionTypeCardTopUpBankFee                      TransactionType = "CardTopUpBankFee"
	TransactionTypeEmoneySubstractionRestore             TransactionType = "EmoneySubstractionRestore"
	TransactionTypeCardPayment                           TransactionType = "CardPayment"
	TransactionTypeRefund                                TransactionType = "Refund"
	TransactionTypeRefundToBankCard                      TransactionType = "RefundToBankCard"
	TransactionTypeStornoUnSuccessfulRefundToBankCard    TransactionType = "StornoUnSuccessfulRefundToBankCard"
	TransactionTypeUnderReview                           TransactionType = "UnderReview"
	TransactionTypeReleaseReview                         TransactionType = "ReleaseReview"
	TransactionTypeBankTransferPayment                   TransactionType = "BankTransferPayment"
	TransactionTypeRefundToBankAccount                   TransactionType = "RefundToBankAccount"
	TransactionTypeStornoUnSuccessfulRefundToBankAccount TransactionType = "StornoUnSuccessfulRefundToBankAccount"
	TransactionTypeBankTransferPaymentFee                TransactionType = "BankTransferPaymentFee"
	TransactionTypeBarionBalanceProcessingFee            TransactionType = "BarionBalanceProcessingFee"
)
